config/routes.rb
Rails.application.routes.draw do
  

   root 'quotes#new'

   get 'quotes/new/games' => 'quotes#get_games'
   get 'quotes/new/parts' => 'quotes#get_parts'
   get 'quotes/search' => 'quotes#search'
   resources :quotes

  resources :rejecteds

  resources :episodes

end

app/models/episode.rb
class Episode < ActiveRecord::Base
has_many :quotes
end

app/models/quote.rb
class Quote < ActiveRecord::Base
belongs_to :episode
end

app/models/rejected.rb
class Rejected < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
      render text: "Hello World!"
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:video_id, :game, :show, :title, :part, :duration, :thumbnail_url)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
	@showlist = Episode.select(:show).distinct
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
	episode = Episode.find_by(game: params[:game], part: params[:part])
    @quote = episode.quotes.new(content: params[:quote][:content], time: params[:quote][:time])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def get_games
	show_name = params[:show_name]
	@games = Episode.select(:game).distinct.where(show: show_name).order(:game)
	respond_to do |format|
		format.json {render json: @games}
	end
  end
  def get_parts
	game_name = params[:game_name]
	@parts = Episode.select(:part).where(game: game_name)
	respond_to do |format|
		format.json {render json: @parts}
	end
  end

  def search
	@quotes = Quote.where(["content like ?","%#{params[:search]}%"])
	render 'quotes/search_results'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:content, :episode_id, :time)
    end
end

app/controllers/rejecteds_controller.rb
class RejectedsController < ApplicationController
  before_action :set_rejected, only: [:show, :edit, :update, :destroy]

  # GET /rejecteds
  # GET /rejecteds.json
  def index
    @rejecteds = Rejected.all
  end

  # GET /rejecteds/1
  # GET /rejecteds/1.json
  def show
  end

  # GET /rejecteds/new
  def new
    @rejected = Rejected.new
  end

  # GET /rejecteds/1/edit
  def edit
  end

  # POST /rejecteds
  # POST /rejecteds.json
  def create
    @rejected = Rejected.new(rejected_params)

    respond_to do |format|
      if @rejected.save
        format.html { redirect_to @rejected, notice: 'Rejected was successfully created.' }
        format.json { render :show, status: :created, location: @rejected }
      else
        format.html { render :new }
        format.json { render json: @rejected.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rejecteds/1
  # PATCH/PUT /rejecteds/1.json
  def update
    respond_to do |format|
      if @rejected.update(rejected_params)
        format.html { redirect_to @rejected, notice: 'Rejected was successfully updated.' }
        format.json { render :show, status: :ok, location: @rejected }
      else
        format.html { render :edit }
        format.json { render json: @rejected.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rejecteds/1
  # DELETE /rejecteds/1.json
  def destroy
    @rejected.destroy
    respond_to do |format|
      format.html { redirect_to rejecteds_url, notice: 'Rejected was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rejected
      @rejected = Rejected.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rejected_params
      params.require(:rejected).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/rejecteds_helper.rb
module RejectedsHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video_id %><br>
    <%= f.text_field :video_id %>
  </div>
  <div class="field">
    <%= f.label :game %><br>
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :show %><br>
    <%= f.text_field :show %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :part %><br>
    <%= f.text_field :part %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :thumbnail_url %><br>
    <%= f.text_field :thumbnail_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>Game</th>
      <th>Show</th>
      <th>Title</th>
      <th>Part</th>
      <th>Duration</th>
      <th>Thumbnail url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.video_id %></td>
        <td><%= episode.game %></td>
        <td><%= episode.show %></td>
        <td><%= episode.title %></td>
        <td><%= episode.part %></td>
        <td><%= episode.duration %></td>
        <td><%= episode.thumbnail_url %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video:</strong>
  <%= @episode.video_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @episode.game %>
</p>

<p>
  <strong>Show:</strong>
  <%= @episode.show %>
</p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Part:</strong>
  <%= @episode.part %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @episode.duration %>
</p>

<p>
  <strong>Thumbnail url:</strong>
  <%= @episode.thumbnail_url %>
</p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GrumpQuotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :episode_id %><br>
    <%= f.number_field :episode_id %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/_searchform.html.erb
<form action='/quotes/search' method='get'>
	<input type='text' id='search' name='search'>
	<input type='submit' value='Search'>
</form>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<%= render 'searchform' %>
<a href='/quotes/new'>Add new quote</a>

app/views/quotes/new.html.erb
<h1>New Quote</h1>
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<label for="show_dropdown">Show</label><br>
	<select id="show_dropdown" name="show">
		<option value="">Select a show</option>
		<% @showlist.each do |item| %>
			<option value="<%= item[:show] %>"><%= item[:show] %></option>
		<% end %>
	</select>
  </div>
  <div class="field">
	<label for="game_dropdown">Game</label><br>
	<select id="game_dropdown" name="game">
		<option value="">Select a game</option>
	</select>
  </div>
  <div class="field">
	<label for="part_dropdown">Part</label><br>
	<select id="part_dropdown" name="part">
		<option value="">Select part</option>
	</select>
  </div>
  <div class="field">
    <label for="quote_content">Quote</label><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
	<i>enter in the form of XhXmXs</i><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', quotes_path %>

app/views/quotes/search_results.html.erb
<%= render 'searchform' %>
<a href='/quotes/new'>Add new quote</a><style>
	td {
		padding-left: 20px;
		padding-right: 20px;
	}
</style>
<table>
	<% @quotes.each do |quote| %>
		<tr>
			<td>
				<a href='https://www.youtube.com/watch?v=<%= quote.episode[:video_id] %>'>
				<img src='<%= quote.episode[:thumbnail_url] %>'>
				</a>
			</td>
			<td>
				<%= quote.episode[:game] %>: <%= quote.episode[:title] %>
			</td>
			<td>
				"<%= quote[:content] %>"
			</td>
			<td>
				<a href='https://www.youtube.com/watch?v=<%= quote.episode[:video_id] %>&t=<%= quote[:time] %>'>
				<%= quote[:time] %>
				</a>
			</td>
		</tr>
	<% end %>
</table>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @quote.content %>
</p>

<p>
  <strong>Episode:</strong>
  <%= @quote.episode_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @quote.time %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/rejecteds/_form.html.erb
<%= form_for(@rejected) do |f| %>
  <% if @rejected.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rejected.errors.count, "error") %> prohibited this rejected from being saved:</h2>

      <ul>
      <% @rejected.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rejecteds/edit.html.erb
<h1>Editing Rejected</h1>

<%= render 'form' %>

<%= link_to 'Show', @rejected %> |
<%= link_to 'Back', rejecteds_path %>

app/views/rejecteds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rejecteds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rejecteds.each do |rejected| %>
      <tr>
        <td><%= rejected.name %></td>
        <td><%= link_to 'Show', rejected %></td>
        <td><%= link_to 'Edit', edit_rejected_path(rejected) %></td>
        <td><%= link_to 'Destroy', rejected, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rejected', new_rejected_path %>

app/views/rejecteds/new.html.erb
<h1>New Rejected</h1>

<%= render 'form' %>

<%= link_to 'Back', rejecteds_path %>

app/views/rejecteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rejected.name %>
</p>

<%= link_to 'Edit', edit_rejected_path(@rejected) %> |
<%= link_to 'Back', rejecteds_path %>